export const locationDropdownItems = [
  { id: 1, locationname: "All Locations", location: "" },
  { id: 2, locationname: "Antalya", location: "Antalya" },
  { id: 3, locationname: "Bodrum", location: "Bodrum" },
  { id: 4, locationname: "Marmaris", location: "Marmaris" },
  { id: 5, locationname: "Kemer", location: "Kemer" },
];

export const purchaseDropdownItems = [
  { purchaseoptionname: "All Options", purchaseoption: "" },
  { purchaseoptionname: "For Sale", purchaseoption: "For Sale" },
  { purchaseoptionname: "For Rent", purchaseoption: "For Rent" },
];

export const homeDropdownItems = [
  { homeoptionname: "All Properties", homeoption: "" },
  { homeoptionname: "Villa", homeoption: "Villa" },
  { homeoptionname: "Apart", homeoption: "Apart" },
];

export const minpriceDropdownItems = [
  { minpriceoption: "0", minpriceoptionname: "0" },
  { minpriceoption: "50000", minpriceoptionname: "50000" },
  { minpriceoption: "100000", minpriceoptionname: "100000" },
  { minpriceoption: "150000", minpriceoptionname: "150000" },
  { minpriceoption: "200000", minpriceoptionname: "200000" },
];

export const maxpriceDropdownItems = [
  { maxpriceoption: "50000", maxpriceoptionname: "50000" },
  { maxpriceoption: "100000", maxpriceoptionname: "100000" },
  { maxpriceoption: "150000", maxpriceoptionname: "150000" },
  { maxpriceoption: "200000", maxpriceoptionname: "200000" },
  { maxpriceoption: "250000", maxpriceoptionname: "250000" },
  { maxpriceoption: "300000", maxpriceoptionname: "300000" },
  { maxpriceoption: "350000", maxpriceoptionname: "350000" },
];

export const minroomDropdownItems = [
  { id: 1, minroomoption: "1" },
  { id: 2, minroomoption: "2" },
  { id: 3, minroomoption: "3" },
  { id: 4, minroomoption: "4" },
  { id: 5, minroomoption: "5" },
  { id: 6, minroomoption: "6" },
  { id: 7, minroomoption: "7" },
  { id: 8, minroomoption: "8" },
  { id: 9, minroomoption: "9" },
  { id: 10, minroomoption: "10" },
];

export const maxroomDropdownItems = [
  { id: 1, maxroomoption: "1" },
  { id: 2, maxroomoption: "2" },
  { id: 3, maxroomoption: "3" },
  { id: 4, maxroomoption: "4" },
  { id: 5, maxroomoption: "5" },
  { id: 6, maxroomoption: "7" },
  { id: 7, maxroomoption: "8" },
  { id: 8, maxroomoption: "9" },
  { id: 9, maxroomoption: "10" },
  { id: 10, maxroomoption: "11" },
  { id: 11, maxroomoption: "12" },
];

export const minsizeDropdownItems = [
  { id: "0", minsizeoptionoption: "0 " },
  { id: "1", minsizeoptionoption: "10" },
  { id: "2", minsizeoptionoption: "20" },
  { id: "3", minsizeoptionoption: "30" },
  { id: "4", minsizeoptionoption: "40" },
  { id: "5", minsizeoptionoption: "50" },
  { id: "6", minsizeoptionoption: "60" },
  { id: "7", minsizeoptionoption: "70" },
  { id: "8", minsizeoptionoption: "80" },
  { minsizeoptionoption: "90" },
  { minsizeoptionoption: "100" },
  { minsizeoptionoption: "110" },
  { minsizeoptionoption: "120" },
  { minsizeoptionoption: "130" },
  { minsizeoptionoption: "140" },
  { minsizeoptionoption: "150" },
  { minsizeoptionoption: "160" },
  { minsizeoptionoption: "170" },
  { minsizeoptionoption: "180" },
  { minsizeoptionoption: "190" },
  { minsizeoptionoption: "200" },
  { minsizeoptionoption: "210" },
  { minsizeoptionoption: "220" },
  { minsizeoptionoption: "230" },
  { minsizeoptionoption: "240" },
  { minsizeoptionoption: "250" },
  { minsizeoptionoption: "260" },
  { minsizeoptionoption: "270" },
  { minsizeoptionoption: "280" },
  { minsizeoptionoption: "290" },
  { minsizeoptionoption: "300" },
  { minsizeoptionoption: "310" },
  { minsizeoptionoption: "320" },
];

export const maxsizeDropdownItems = [
  { id: "0m²", maxsizeoption: "0" },
  { id: "10m²", maxsizeoption: "10" },
  { id: "20m²", maxsizeoption: "20" },
  { id: "30m²", maxsizeoption: "30" },
  { id: "40m²", maxsizeoption: "40" },
  { id: "50m²", maxsizeoption: "50" },
  { id: "60m²", maxsizeoption: "60" },
  { id: "70m²", maxsizeoption: "70" },
  { id: "80m²", maxsizeoption: "80" },
  { id: "90m²", maxsizeoption: "90" },
  { id: "100m²", maxsizeoption: "100" },
  { id: "110m²", maxsizeoption: "110" },
  { id: "120m²", maxsizeoption: "120" },
  { id: "130m²", maxsizeoption: "130" },
  { id: "140m²", maxsizeoption: "140" },
  { id: "150m²", maxsizeoption: "150" },
  { id: "160m²", maxsizeoption: "160" },
  { id: "170m²", maxsizeoption: "170" },
  { id: "180m²", maxsizeoption: "180" },
  { id: "190m²", maxsizeoption: "190" },
  { id: "200m²", maxsizeoption: "200" },
  { id: "210m²", maxsizeoption: "210" },
  { id: "220m²", maxsizeoption: "220" },
  { id: "230m²", maxsizeoption: "230" },
  { id: "240m²", maxsizeoption: "240" },
  { id: "250m²", maxsizeoption: "250" },
  { id: "260m²", maxsizeoption: "260" },
  { id: "270m²", maxsizeoption: "270" },
  { id: "280m²", maxsizeoption: "280" },
  { id: "290m²", maxsizeoption: "290" },
  { id: "300m²", maxsizeoption: "300" },
  { id: "310m²", maxsizeoption: "310" },
  { id: "320m²", maxsizeoption: "320" },
];
